services:
  - type: web
    name: sistema-de-vendas-frontend
    env: static
    buildCommand: npm install --force && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sistema-de-vendas-backend.onrender.com
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 