services:
  - type: web
    name: sistema-de-vendas-frontend
    env: static
    buildCommand: npm install --force && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sistema-de-vendas-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html 